# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161116_2243_squashed_0003_auto_20161116_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='places',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
