# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_last_seen_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('key', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('value', models.TextField()),
            ],
        ),
    ]
