# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_event_places'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='list',
            new_name='event',
        ),
    ]
