# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_setting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_at',
            new_name='start_at',
        ),
        migrations.AddField(
            model_name='event',
            name='end_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
