# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170403_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ended_at',
        ),
        migrations.AddField(
            model_name='event',
            name='calendar_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
