# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161122_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='note_field',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
