# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 19:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20161127_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set([('event', 'participant')]),
        ),
    ]
