# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20161202_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='email',
            field=models.EmailField(default='noreply@alembic.utwente.nl', max_length=254),
            preserve_default=False,
        ),
    ]
