# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-12 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170411_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['updated_at']},
        ),
        migrations.AlterField(
            model_name='event',
            name='deadline_at',
            field=models.DateTimeField(),
        ),
    ]
