# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 21:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_committee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='places',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
