# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-12 21:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170703_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='note_field_options',
            field=models.CharField(blank=True, default='', max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
