# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 15:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_auto_20161214_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='members',
            field=models.ManyToManyField(related_name='in_committees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='committee',
            name='chairman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chaired_committees', to=settings.AUTH_USER_MODEL),
        ),
    ]
