# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-08 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170216_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='super_members',
            field=models.BooleanField(default=False),
        ),
    ]
