# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-13 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170713_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='note_field_public',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='note_field_required',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
